//  Dungeons and Dragons v3.5 Digital Character Sheet
//  Copyright (C) 2003-2023 Mattie Schraeder
//  https://afrozenpeach.net
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
#include <jpeg.hpp>
#include <Menus.hpp>
#include <Dialogs.hpp>
#include <Graphics.hpp>
#include <Grids.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
        TMainMenu *MainMenu1;
        TMenuItem *File1;
        TMenuItem *About1;
        TMenuItem *Load1;
        TMenuItem *Save1;
        TMenuItem *N1;
        TMenuItem *Exit1;
        TOpenDialog *OpenDialog1;
        TSaveDialog *SaveDialog1;
        TMenuItem *Print1;
        TMenuItem *N2;
        TPrintDialog *PrintDialog1;
        TMenuItem *GoToPage1;
        TMenuItem *Page11;
        TMenuItem *Page21;
        TMenuItem *Page31;
        TMenuItem *Saveas1;
        TMenuItem *N3;
        TMenuItem *Importv1XSheet1;
        TMenuItem *ReverttoLastSave1;
        TMenuItem *Importv2XSheet1;
        TMenuItem *Help1;
        TTabSheet *TabSheet1;
        TImage *Page1BG;
        TLabel *FlatfootAC;
        TLabel *AppraiseModL;
        TLabel *BalanceModL;
        TLabel *BluffModL;
        TLabel *ClimbModL;
        TLabel *ConcentrationModL;
        TLabel *Craft1ModL;
        TLabel *Craft2ModL;
        TLabel *Craft3ModL;
        TLabel *DecipherModL;
        TLabel *DiplomacyModL;
        TLabel *DisableModL;
        TLabel *DisguiseModL;
        TLabel *EscapeModL;
        TLabel *ForgeryModL;
        TLabel *GatherModL;
        TLabel *HandleModL;
        TLabel *HealModL;
        TLabel *HideModL;
        TLabel *IntimidateModL;
        TLabel *JumpModL;
        TLabel *Knowledge1ModL;
        TLabel *Knowledge2ModL;
        TLabel *Knowledge3ModL;
        TLabel *Knowledge4ModL;
        TLabel *Knowledge5ModL;
        TLabel *ListenModL;
        TLabel *MoveModL;
        TLabel *OpenModL;
        TLabel *Perform1ModL;
        TLabel *Perform2ModL;
        TLabel *Perform3ModL;
        TLabel *Profession1ModL;
        TLabel *Profession2ModL;
        TLabel *RideModL;
        TLabel *SearchModL;
        TLabel *SenseModL;
        TLabel *SleightModL;
        TLabel *SpellcraftModL;
        TLabel *SpotModL;
        TLabel *SurvivalModL;
        TLabel *SwimModL;
        TLabel *TumbleModL;
        TLabel *UseMagicModL;
        TLabel *UseRopeModL;
        TLabel *Misc1ModL;
        TLabel *Misc2ModL;
        TLabel *Misc3ModL;
        TLabel *ACTotalL;
        TLabel *TouchAC;
        TLabel *InitModL;
        TLabel *FortModL;
        TLabel *RefModL;
        TLabel *WillModL;
        TLabel *GrappleMod;
        TLabel *ACArmorBonusL;
        TLabel *ACShieldBonusL;
        TLabel *ACDexModL;
        TLabel *InitDexModL;
        TLabel *FortConModL;
        TLabel *RefDexModL;
        TLabel *WillWisModL;
        TLabel *GrappleBAB;
        TLabel *GrappleStrMod;
        TLabel *AppraiseAbilityModL;
        TLabel *BalanceAbilityModL;
        TLabel *ClimbAbilityModL;
        TLabel *BluffAbilityModL;
        TLabel *Craft3AbilityModL;
        TLabel *Craft2AbilityModL;
        TLabel *Craft1AbilityModL;
        TLabel *ConcentrationAbilityModL;
        TLabel *DisguiseAbilityModL;
        TLabel *DisableAbilityModL;
        TLabel *DiplomacyAbilityModL;
        TLabel *DecipherAbilityModL;
        TLabel *HandleAbilityModL;
        TLabel *GatherAbilityModL;
        TLabel *ForgeryAbilityModL;
        TLabel *EscapeAbilityModL;
        TLabel *Knowledge3AbilityModL;
        TLabel *Knowledge4AbilityModL;
        TLabel *Knowledge5AbilityModL;
        TLabel *ListenAbilityModL;
        TLabel *Knowledge1AbilityModL;
        TLabel *Knowledge2AbilityModL;
        TLabel *JumpAbilityModL;
        TLabel *IntimidateAbilityModL;
        TLabel *HideAbilityModL;
        TLabel *HealAbilityModL;
        TLabel *Profession2AbilityModL;
        TLabel *RideAbilityModL;
        TLabel *SearchAbilityModL;
        TLabel *SenseAbilityModL;
        TLabel *Perform3AbilityModL;
        TLabel *Profession1AbilityModL;
        TLabel *Perform2AbilityModL;
        TLabel *Perform1AbilityModL;
        TLabel *OpenAbilityModL;
        TLabel *MoveAbilityModL;
        TLabel *UseMagicAbilityModL;
        TLabel *UseRopeAbilityModL;
        TLabel *SwimAbilityModL;
        TLabel *TumbleAbilityModL;
        TLabel *SurvivalAbilityModL;
        TLabel *SpotAbilityModL;
        TLabel *SpellcraftAbilityModL;
        TLabel *SleightAbilityModL;
        TLabel *StrModL;
        TLabel *DexModL;
        TLabel *ConModL;
        TLabel *IntModL;
        TLabel *WisModL;
        TLabel *ChaModL;
        TLabel *StrTModL;
        TLabel *DexTModL;
        TLabel *ConTModL;
        TLabel *IntTModL;
        TLabel *WisTModL;
        TLabel *ChaTModL;
        TLabel *ACSizeMod;
        TLabel *GrappleSizeMod;
        TEdit *StrScr;
        TEdit *RefTemp;
        TEdit *WillTemp;
        TEdit *FortTemp;
        TEdit *Wounds;
        TEdit *Nonlethal;
        TEdit *Speed;
        TEdit *DamageReduction;
        TEdit *MaxRanks;
        TMemo *CondSave;
        TEdit *ClassLevel;
        TEdit *Race;
        TEdit *Alignment;
        TEdit *Deity;
        TEdit *Age;
        TEdit *Gender;
        TEdit *Height;
        TEdit *Weight;
        TEdit *Eyes;
        TEdit *Hair;
        TEdit *Skin;
        TCheckBox *AppraiseCheck;
        TCheckBox *BalanceCheck;
        TCheckBox *BluffCheck;
        TCheckBox *ClimbCheck;
        TCheckBox *ConcentrationCheck;
        TCheckBox *GatherCheck;
        TCheckBox *ForgeryCheck;
        TCheckBox *EscapeCheck;
        TCheckBox *DisguiseCheck;
        TCheckBox *DisableCheck;
        TCheckBox *ListenCheck;
        TCheckBox *MoveCheck;
        TCheckBox *OpenCheck;
        TCheckBox *Perform1Check;
        TCheckBox *Perform2Check;
        TCheckBox *Perform3Check;
        TCheckBox *Profession1Check;
        TCheckBox *Profession2Check;
        TCheckBox *RideCheck;
        TCheckBox *SearchCheck;
        TCheckBox *SenseCheck;
        TCheckBox *SleightCheck;
        TCheckBox *SpellcraftCheck;
        TCheckBox *SpotCheck;
        TCheckBox *SurvivalCheck;
        TCheckBox *SwimCheck;
        TCheckBox *TumbleCheck;
        TCheckBox *UseMagicCheck;
        TCheckBox *UseRopeCheck;
        TCheckBox *Misc1Check;
        TEdit *StrTScr;
        TEdit *DexTScr;
        TEdit *DexScr;
        TEdit *ConScr;
        TEdit *ConTScr;
        TEdit *IntTScr;
        TEdit *IntScr;
        TEdit *WisScr;
        TEdit *WisTScr;
        TEdit *ChaTScr;
        TEdit *ChaScr;
        TEdit *FortBase;
        TEdit *FortMagic;
        TEdit *FortMiscMod;
        TEdit *RefMiscMod;
        TEdit *RefMagic;
        TEdit *RefBase;
        TEdit *WillBase;
        TEdit *WillMagic;
        TEdit *WillMiscMod;
        TEdit *BAB;
        TEdit *SpellResistance;
        TEdit *GrappleMiscMod;
        TCheckBox *Craft1Check;
        TCheckBox *Craft2Check;
        TCheckBox *Craft3Check;
        TCheckBox *DecipherCheck;
        TCheckBox *DiplomacyCheck;
        TCheckBox *HandleCheck;
        TCheckBox *HealCheck;
        TCheckBox *HideCheck;
        TCheckBox *IntimidateCheck;
        TCheckBox *JumpCheck;
        TCheckBox *Knowledge1Check;
        TCheckBox *Knowledge2Check;
        TCheckBox *Knowledge3Check;
        TCheckBox *Knowledge4Check;
        TCheckBox *Knowledge5Check;
        TEdit *Weapon1Name;
        TEdit *Weapon1Bonus;
        TEdit *Weapon1Damage;
        TEdit *Weapon1Crit;
        TEdit *Weapon1Notes;
        TEdit *Weapon1Ammo;
        TEdit *Weapon1Type;
        TEdit *Weapon1Range;
        TEdit *Weapon2Range;
        TEdit *Weapon2Type;
        TEdit *Weapon2Notes;
        TEdit *Weapon2Ammo;
        TEdit *Weapon3Name;
        TEdit *Weapon3Bonus;
        TEdit *Weapon3Damage;
        TEdit *Weapon3Crit;
        TEdit *Weapon2Crit;
        TEdit *Weapon2Damage;
        TEdit *Weapon2Bonus;
        TEdit *Weapon2Name;
        TEdit *Weapon3Range;
        TEdit *Weapon3Type;
        TEdit *Weapon3Notes;
        TEdit *Weapon3Ammo;
        TEdit *Weapon4Name;
        TEdit *Weapon4Bonus;
        TEdit *Weapon4Damage;
        TEdit *Weapon4Crit;
        TEdit *Weapon4Notes;
        TEdit *Weapon4Type;
        TEdit *Weapon4Range;
        TEdit *Weapon4Ammo;
        TEdit *Weapon5Name;
        TEdit *Weapon5Bonus;
        TEdit *Weapon5Damage;
        TEdit *Weapon5Crit;
        TEdit *Weapon5Notes;
        TEdit *Weapon5Type;
        TEdit *Weapon5Range;
        TEdit *Weapon5Ammo;
        TCheckBox *Misc2Check;
        TCheckBox *Misc3Check;
        TEdit *AppraiseRanks;
        TEdit *BalanceRanks;
        TEdit *BluffRanks;
        TEdit *ClimbRanks;
        TEdit *ConcentrationRanks;
        TEdit *Craft1Ranks;
        TEdit *Craft2Ranks;
        TEdit *Craft3Ranks;
        TEdit *DecipherRanks;
        TEdit *DiplomacyRanks;
        TEdit *DisableRanks;
        TEdit *DisguiseRanks;
        TEdit *EscapeRanks;
        TEdit *ForgeryRanks;
        TEdit *GatherRanks;
        TEdit *HandleRanks;
        TEdit *HealRanks;
        TEdit *HideRanks;
        TEdit *IntimidateRanks;
        TEdit *JumpRanks;
        TEdit *Knowledge1Ranks;
        TEdit *Knowledge2Ranks;
        TEdit *Knowledge3Ranks;
        TEdit *Knowledge4Ranks;
        TEdit *Knowledge5Ranks;
        TEdit *ListenRanks;
        TEdit *MoveRanks;
        TEdit *OpenRanks;
        TEdit *Perform1Ranks;
        TEdit *Perform2Ranks;
        TEdit *Perform3Ranks;
        TEdit *Profession1Ranks;
        TEdit *Profession2Ranks;
        TEdit *RideRanks;
        TEdit *SearchRanks;
        TEdit *SenseRanks;
        TEdit *SleightRanks;
        TEdit *SpellcraftRanks;
        TEdit *SpotRanks;
        TEdit *SurvivalRanks;
        TEdit *SwimRanks;
        TEdit *TumbleRanks;
        TEdit *UseMagicRanks;
        TEdit *UseRopeRanks;
        TEdit *Misc1Ranks;
        TEdit *Misc2Ranks;
        TEdit *Misc3Ranks;
        TEdit *AppraiseMisc;
        TEdit *BalanceMisc;
        TEdit *BluffMisc;
        TEdit *ClimbMisc;
        TEdit *ConcentrationMisc;
        TEdit *Craft1Misc;
        TEdit *Craft2Misc;
        TEdit *Craft3Misc;
        TEdit *DecipherMisc;
        TEdit *DiplomacyMisc;
        TEdit *DisableMisc;
        TEdit *DisguiseMisc;
        TEdit *EscapeMisc;
        TEdit *ForgeryMisc;
        TEdit *GatherMisc;
        TEdit *HandleMisc;
        TEdit *HealMisc;
        TEdit *HideMisc;
        TEdit *IntimidateMisc;
        TEdit *JumpMisc;
        TEdit *Knowledge1Misc;
        TEdit *Knowledge2Misc;
        TEdit *Knowledge3Misc;
        TEdit *Knowledge4Misc;
        TEdit *Knowledge5Misc;
        TEdit *ListenMisc;
        TEdit *MoveMisc;
        TEdit *OpenMisc;
        TEdit *Perform1Misc;
        TEdit *Perform2Misc;
        TEdit *Perform3Misc;
        TEdit *Profession1Misc;
        TEdit *Profession2Misc;
        TEdit *RideMisc;
        TEdit *SearchMisc;
        TEdit *SenseMisc;
        TEdit *SleightMisc;
        TEdit *SpellcraftMisc;
        TEdit *SpotMisc;
        TEdit *SurvivalMisc;
        TEdit *SwimMisc;
        TEdit *TumbleMisc;
        TEdit *UseMagicMisc;
        TEdit *UseRopeMisc;
        TEdit *Misc1Misc;
        TEdit *Misc2Misc;
        TEdit *Misc3Misc;
        TEdit *Misc1Ability;
        TEdit *Misc2Ability;
        TEdit *Misc3Ability;
        TEdit *Craft1Edit;
        TEdit *Craft2Edit;
        TEdit *Craft3Edit;
        TEdit *Knowledge1Edit;
        TEdit *Knowledge2Edit;
        TEdit *Knowledge3Edit;
        TEdit *Knowledge4Edit;
        TEdit *Knowledge5Edit;
        TEdit *Perform1Edit;
        TEdit *Perform2Edit;
        TEdit *Perform3Edit;
        TEdit *Profession1Edit;
        TEdit *Profession2Edit;
        TEdit *Misc1Edit;
        TEdit *Misc2Edit;
        TEdit *Misc3Edit;
        TEdit *HP;
        TEdit *NaturalArmor;
        TEdit *DeflectionMod;
        TEdit *ArmorMiscMod;
        TEdit *InitMiscMod;
        TEdit *CharName;
        TEdit *Player;
        TComboBox *Size;
        TTabSheet *TabSheet2;
        TImage *Page2BG;
        TLabel *SpellFailureL;
        TLabel *SpellSave0;
        TLabel *SpellSave1;
        TLabel *SpellSave2;
        TLabel *SpellSave3;
        TLabel *SpellSave4;
        TLabel *SpellSave5;
        TLabel *SpellSave6;
        TLabel *SpellSave7;
        TLabel *SpellSave8;
        TLabel *SpellSave9;
        TLabel *LightLoad;
        TLabel *MediumLoad;
        TLabel *HeavyLoad;
        TLabel *LiftOverHead;
        TLabel *LiftOffGround;
        TLabel *PushDrag;
        TLabel *SpellSaveMod;
        TEdit *ArmorCheck;
        TEdit *ArmorType;
        TEdit *ArmorAC;
        TEdit *ArmorDex;
        TEdit *ArmorName;
        TEdit *ArmorSpeed;
        TEdit *ArmorWeight;
        TEdit *ArmorSpecial;
        TEdit *ShieldName;
        TEdit *ArmorSpellFailure;
        TEdit *ShieldAC;
        TEdit *ShieldWeight;
        TEdit *ShieldCheck;
        TEdit *ShieldSpellFailure;
        TEdit *ShieldSpecial;
        TEdit *Experience;
        TEdit *Campaign;
        TEdit *Protective1Name;
        TEdit *Protective1AC;
        TEdit *Protective1Weight;
        TEdit *Protective1Special;
        TEdit *Protective2Special;
        TEdit *Protective2Weight;
        TEdit *Protective2AC;
        TEdit *Protective2Name;
        TEdit *DomainSchool;
        TMemo *Spells;
        TMemo *Feats;
        TMemo *SpecialAbilities;
        TMemo *Languages;
        TMemo *Money;
        TMemo *OtherPossessions;
        TEdit *SpellsKnown1;
        TEdit *SpellsKnown0;
        TEdit *SpellsKnown2;
        TEdit *SpellsKnown3;
        TEdit *SpellsKnown7;
        TEdit *SpellsKnown6;
        TEdit *SpellsKnown5;
        TEdit *SpellsKnown4;
        TEdit *SpellsKnown8;
        TEdit *SpellsKnown9;
        TEdit *SpellsDay9;
        TEdit *SpellsDay8;
        TEdit *SpellsDay7;
        TEdit *SpellsDay6;
        TEdit *SpellsDay5;
        TEdit *SpellsDay4;
        TEdit *SpellsDay3;
        TEdit *SpellsDay2;
        TEdit *SpellsDay1;
        TEdit *SpellsDay0;
        TEdit *BonusSpells1;
        TEdit *BonusSpells2;
        TEdit *BonusSpells3;
        TEdit *BonusSpells4;
        TEdit *BonusSpells5;
        TEdit *BonusSpells6;
        TEdit *BonusSpells7;
        TEdit *BonusSpells8;
        TEdit *BonusSpells9;
        TMemo *SpellCondMod;
        TComboBox *SpellSaveAbility;
        TTabSheet *TabSheet3;
        TImage *Image1;
        TTabSheet *TabSheet4;
        TImage *Image2;
        TTabSheet *TabSheet5;
        TMemo *MiscNotes;
        TTabSheet *TabSheet6;
        TImage *Image3;
        TTabSheet *TabSheet7;
        TButton *RollSTR;
        TButton *RollDEX;
        TButton *RollCON;
        TButton *RollINT;
        TButton *RollWIS;
        TButton *RollCHA;
        TButton *RollInit;
        TButton *RollFort;
        TButton *RollReflex;
        TButton *RollWill;
        TButton *RollGrapple;
        TButton *RollAttack1;
        TButton *RollAttack2;
        TButton *RollAttack3;
        TButton *RollAttack4;
        TButton *RollAttack5;
        TButton *RollDamage1;
        TButton *RollDamage2;
        TButton *RollDamage3;
        TButton *RollDamage4;
        TButton *RollDamage5;
        TButton *RollAppraise;
        TButton *RollBalance;
        TButton *RollBluff;
        TButton *RollClimb;
        TButton *RollConcentration;
        TButton *RollCraft1;
        TButton *RollCraft2;
        TButton *RollCraft3;
        TButton *RollDecipherScript;
        TButton *RollDiplomacy;
        TButton *RollDisableDevice;
        TButton *RollDisguise;
        TButton *Button13;
        TButton *RollForgery;
        TButton *Button15;
        TButton *RollHandleAnimal;
        TButton *RollHeal;
        TButton *RollHide;
        TButton *RollIntimidate;
        TButton *RollJump;
        TButton *RollKnowledge1;
        TButton *RollKnowledge2;
        TButton *RollKnowledge3;
        TButton *RollKnowledge4;
        TButton *RollProfession1;
        TButton *RollPerform3;
        TButton *RollPerform2;
        TButton *RollPerform1;
        TButton *RollOpenLock;
        TButton *RollMoveSilent;
        TButton *RollListen;
        TButton *RollKnowledge5;
        TButton *RollSurvival;
        TButton *RollSpot;
        TButton *RollSpellcraft;
        TButton *RollSleightofHand;
        TButton *RollSenseMotive;
        TButton *RollSearch;
        TButton *RollRide;
        TButton *RollProfession2;
        TButton *RollSwim;
        TButton *RollTumble;
        TButton *RollUseMagicDevice;
        TButton *RollUseRope;
        TButton *RollCustom1;
        TButton *RollCustom2;
        TButton *RollCustom3;
        TButton *Rolld4;
        TEdit *Numd4;
        TEdit *Numd6;
        TButton *Rolld6;
        TEdit *Numd8;
        TButton *Rolld8;
        TButton *Rolld10;
        TEdit *Numd10;
        TEdit *Numd20;
        TButton *Rolld20;
        TButton *Rolld12;
        TEdit *Numd12;
        TEdit *Numd100;
        TButton *Rolld100;
        TMenuItem *Export1;
        TMenuItem *HTML1;
        TMenuItem *TXT1;
        TMenuItem *RTF1;
        TListBox *RollLog;
        TMenuItem *DiceRoller1;
        TMenuItem *Options1;
        TMenuItem *AllFontOptions;
        TFontDialog *FontDialog1;
        TMenuItem *N4;
        TMenuItem *LabelFonts1;
        TMenuItem *TextboxFonts1;
        TMenuItem *SmallMemoFonts1;
        TMenuItem *LargeMemoFonts1;
        TMenuItem *Page3Font1;
        TMenuItem *N5;
        TCheckBox *Misc3ACPCheck;
        TCheckBox *Misc2ACPCheck;
        TCheckBox *Misc1ACPCheck;
        TLabel *Misc3AbilityModL;
        TLabel *Misc2AbilityModL;
        TLabel *Misc1AbilityModL;
        TMenuItem *DiceRollerLog1;
        TButton *RollMelee;
        TButton *RollRanged;
        TImage *Page1BGLarge;
        TImage *Page2BGLarge;
        TMenuItem *Scaleto10241;
        TMenuItem *N6;
        TButton *RollStats;
        TMenuItem *Importv20Save1;
        TPageControl *PageControl1;
        TMenuItem *BMPImageFile1;
        TMenuItem *Importv30Save1;
        TMenuItem *XMLMapToolMacroXML1;
        TMenuItem *ResetFonts1;
        TFontDialog *LabelFont;
        TFontDialog *TextBoxFont;
        TFontDialog *SmallMemoFont;
        TFontDialog *LargeMemoFont;
        TFontDialog *MiscNoteFont;
        TFontDialog *RollLogFont;
        void __fastcall Exit1Click(TObject *Sender);
        void __fastcall Save1Click(TObject *Sender);
        void __fastcall Load1Click(TObject *Sender);
        void __fastcall About1Click(TObject *Sender);
        void __fastcall CharNameChange(TObject *Sender);
        void __fastcall StrScrChange(TObject *Sender);
        void __fastcall DexScrChange(TObject *Sender);
        void __fastcall ConScrChange(TObject *Sender);
        void __fastcall IntScrChange(TObject *Sender);
        void __fastcall WisScrChange(TObject *Sender);
        void __fastcall ChaScrChange(TObject *Sender);
        void __fastcall ArmorACChange(TObject *Sender);
        void __fastcall ShieldACChange(TObject *Sender);
        void __fastcall BABChange(TObject *Sender);
        void __fastcall GrappleSizeModChange(TObject *Sender);
        void __fastcall GrappleMiscModChange(TObject *Sender);
        void __fastcall FortBaseChange(TObject *Sender);
        void __fastcall FortMagicChange(TObject *Sender);
        void __fastcall FortMiscModChange(TObject *Sender);
        void __fastcall FortTempChange(TObject *Sender);
        void __fastcall RefBaseChange(TObject *Sender);
        void __fastcall RefMagicChange(TObject *Sender);
        void __fastcall RefMiscModChange(TObject *Sender);
        void __fastcall RefTempChange(TObject *Sender);
        void __fastcall WillBaseChange(TObject *Sender);
        void __fastcall WillMagicChange(TObject *Sender);
        void __fastcall WillMiscModChange(TObject *Sender);
        void __fastcall WillTempChange(TObject *Sender);
        void __fastcall InitMiscModChange(TObject *Sender);
        void __fastcall ACSizeModChange(TObject *Sender);
        void __fastcall NaturalArmorChange(TObject *Sender);
        void __fastcall DeflectionModChange(TObject *Sender);
        void __fastcall ArmorMiscModChange(TObject *Sender);
        void __fastcall AppraiseRanksChange(TObject *Sender);
        void __fastcall AppraiseMiscChange(TObject *Sender);
        void __fastcall BalanceRanksChange(TObject *Sender);
        void __fastcall BalanceMiscChange(TObject *Sender);
        void __fastcall BluffRanksChange(TObject *Sender);
        void __fastcall BluffMiscChange(TObject *Sender);
        void __fastcall ClimbRanksChange(TObject *Sender);
        void __fastcall ClimbMiscChange(TObject *Sender);
        void __fastcall ConcentrationRanksChange(TObject *Sender);
        void __fastcall ConcentrationMiscChange(TObject *Sender);
        void __fastcall Craft1RanksChange(TObject *Sender);
        void __fastcall Craft1MiscChange(TObject *Sender);
        void __fastcall Craft2RanksChange(TObject *Sender);
        void __fastcall Craft2MiscChange(TObject *Sender);
        void __fastcall Craft3RanksChange(TObject *Sender);
        void __fastcall Craft3MiscChange(TObject *Sender);
        void __fastcall DecipherRanksChange(TObject *Sender);
        void __fastcall DecipherMiscChange(TObject *Sender);
        void __fastcall DiplomacyRanksChange(TObject *Sender);
        void __fastcall DiplomacyMiscChange(TObject *Sender);
        void __fastcall DisableRanksChange(TObject *Sender);
        void __fastcall DisableMiscChange(TObject *Sender);
        void __fastcall DisguiseRanksChange(TObject *Sender);
        void __fastcall DisguiseMiscChange(TObject *Sender);
        void __fastcall EscapeRanksChange(TObject *Sender);
        void __fastcall EscapeMiscChange(TObject *Sender);
        void __fastcall ForgeryRanksChange(TObject *Sender);
        void __fastcall ForgeryMiscChange(TObject *Sender);
        void __fastcall GatherRanksChange(TObject *Sender);
        void __fastcall GatherMiscChange(TObject *Sender);
        void __fastcall HandleRanksChange(TObject *Sender);
        void __fastcall HandleMiscChange(TObject *Sender);
        void __fastcall HealRanksChange(TObject *Sender);
        void __fastcall HealMiscChange(TObject *Sender);
        void __fastcall HideRanksChange(TObject *Sender);
        void __fastcall HideMiscChange(TObject *Sender);
        void __fastcall IntimidateRanksChange(TObject *Sender);
        void __fastcall IntimidateMiscChange(TObject *Sender);
        void __fastcall JumpRanksChange(TObject *Sender);
        void __fastcall JumpMiscChange(TObject *Sender);
        void __fastcall Knowledge1RanksChange(TObject *Sender);
        void __fastcall Knowledge1MiscChange(TObject *Sender);
        void __fastcall Knowledge2RanksChange(TObject *Sender);
        void __fastcall Knowledge2MiscChange(TObject *Sender);
        void __fastcall Knowledge3RanksChange(TObject *Sender);
        void __fastcall Knowledge3MiscChange(TObject *Sender);
        void __fastcall Knowledge4RanksChange(TObject *Sender);
        void __fastcall Knowledge4MiscChange(TObject *Sender);
        void __fastcall Knowledge5RanksChange(TObject *Sender);
        void __fastcall Knowledge5MiscChange(TObject *Sender);
        void __fastcall ListenRanksChange(TObject *Sender);
        void __fastcall ListenMiscChange(TObject *Sender);
        void __fastcall MoveRanksChange(TObject *Sender);
        void __fastcall MoveMiscChange(TObject *Sender);
        void __fastcall OpenRanksChange(TObject *Sender);
        void __fastcall OpenMiscChange(TObject *Sender);
        void __fastcall Perform1RanksChange(TObject *Sender);
        void __fastcall Perform1MiscChange(TObject *Sender);
        void __fastcall Perform2RanksChange(TObject *Sender);
        void __fastcall Perform2MiscChange(TObject *Sender);
        void __fastcall Perform3RanksChange(TObject *Sender);
        void __fastcall Perform3MiscChange(TObject *Sender);
        void __fastcall Profession1RanksChange(TObject *Sender);
        void __fastcall Profession1MiscChange(TObject *Sender);
        void __fastcall Profession2RanksChange(TObject *Sender);
        void __fastcall Profession2MiscChange(TObject *Sender);
        void __fastcall RideRanksChange(TObject *Sender);
        void __fastcall RideMiscChange(TObject *Sender);
        void __fastcall SearchRanksChange(TObject *Sender);
        void __fastcall SearchMiscChange(TObject *Sender);
        void __fastcall SenseRanksChange(TObject *Sender);
        void __fastcall SenseMiscChange(TObject *Sender);
        void __fastcall SleightRanksChange(TObject *Sender);
        void __fastcall SleightMiscChange(TObject *Sender);
        void __fastcall SpellcraftRanksChange(TObject *Sender);
        void __fastcall SpellcraftMiscChange(TObject *Sender);
        void __fastcall SpotRanksChange(TObject *Sender);
        void __fastcall SpotMiscChange(TObject *Sender);
        void __fastcall SurvivalRanksChange(TObject *Sender);
        void __fastcall SurvivalMiscChange(TObject *Sender);
        void __fastcall SwimRanksChange(TObject *Sender);
        void __fastcall SwimMiscChange(TObject *Sender);
        void __fastcall TumbleRanksChange(TObject *Sender);
        void __fastcall TumbleMiscChange(TObject *Sender);
        void __fastcall UseMagicRanksChange(TObject *Sender);
        void __fastcall UseMagicMiscChange(TObject *Sender);
        void __fastcall UseRopeRanksChange(TObject *Sender);
        void __fastcall UseRopeMiscChange(TObject *Sender);
        void __fastcall Misc1RanksChange(TObject *Sender);
        void __fastcall Misc1MiscChange(TObject *Sender);
        void __fastcall Misc2RanksChange(TObject *Sender);
        void __fastcall Misc2MiscChange(TObject *Sender);
        void __fastcall Misc3RanksChange(TObject *Sender);
        void __fastcall Misc3MiscChange(TObject *Sender);
        void __fastcall StrTScrChange(TObject *Sender);
        void __fastcall DexTScrChange(TObject *Sender);
        void __fastcall ConTScrChange(TObject *Sender);
        void __fastcall IntTScrChange(TObject *Sender);
        void __fastcall WisTScrChange(TObject *Sender);
        void __fastcall ChaTScrChange(TObject *Sender);
        void __fastcall ArmorSpellFailureChange(TObject *Sender);
        void __fastcall ShieldSpellFailureChange(TObject *Sender);
        void __fastcall Print1Click(TObject *Sender);
        void __fastcall Page11Click(TObject *Sender);
        void __fastcall Page21Click(TObject *Sender);
        void __fastcall Page31Click(TObject *Sender);
        void __fastcall Saveas1Click(TObject *Sender);
        void __fastcall SpellSaveAbilityChange(TObject *Sender);
        void __fastcall Importv1XSheet1Click(TObject *Sender);
        void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall ReverttoLastSave1Click(TObject *Sender);
        void __fastcall Importv2XSheet1Click(TObject *Sender);
        void __fastcall SizeChange(TObject *Sender);
        void __fastcall ArmorDexChange(TObject *Sender);
        void __fastcall PageControl1Change(TObject *Sender);
        void __fastcall DiceRoller1Click(TObject *Sender);
        void __fastcall ArmorCheckChange(TObject *Sender);
        void __fastcall AllFontOptionsClick(TObject *Sender);
        void __fastcall FontDialog1Apply(TObject *Sender, HWND Wnd);
        void __fastcall LabelFonts1Click(TObject *Sender);
        void __fastcall TextboxFonts1Click(TObject *Sender);
        void __fastcall SmallMemoFonts1Click(TObject *Sender);
        void __fastcall LargeMemoFonts1Click(TObject *Sender);
        void __fastcall Page3Font1Click(TObject *Sender);
        void __fastcall Misc3AbilityChange(TObject *Sender);
        void __fastcall Misc1AbilityChange(TObject *Sender);
        void __fastcall Misc2AbilityChange(TObject *Sender);
        void __fastcall Misc1ACPCheckClick(TObject *Sender);
        void __fastcall Misc2ACPCheckClick(TObject *Sender);
        void __fastcall Misc3ACPCheckClick(TObject *Sender);
        void __fastcall Craft1EditChange(TObject *Sender);
        void __fastcall Craft2EditChange(TObject *Sender);
        void __fastcall Craft3EditChange(TObject *Sender);
        void __fastcall Knowledge1EditChange(TObject *Sender);
        void __fastcall Knowledge2EditChange(TObject *Sender);
        void __fastcall Knowledge3EditChange(TObject *Sender);
        void __fastcall Knowledge4EditChange(TObject *Sender);
        void __fastcall Knowledge5EditChange(TObject *Sender);
        void __fastcall Perform1EditChange(TObject *Sender);
        void __fastcall Perform2EditChange(TObject *Sender);
        void __fastcall Perform3EditChange(TObject *Sender);
        void __fastcall Profession1EditChange(TObject *Sender);
        void __fastcall Profession2EditChange(TObject *Sender);
        void __fastcall Misc1EditChange(TObject *Sender);
        void __fastcall Misc2EditChange(TObject *Sender);
        void __fastcall Misc3EditChange(TObject *Sender);
        void __fastcall RollSTRClick(TObject *Sender);
        void __fastcall DiceRollerLog1Click(TObject *Sender);
        void __fastcall Scaleto10241Click(TObject *Sender);
        void __fastcall RollDEXClick(TObject *Sender);
        void __fastcall RollCONClick(TObject *Sender);
        void __fastcall RollINTClick(TObject *Sender);
        void __fastcall RollWISClick(TObject *Sender);
        void __fastcall RollCHAClick(TObject *Sender);
        void __fastcall RollStatsClick(TObject *Sender);
        void __fastcall ShieldCheckChange(TObject *Sender);
        void __fastcall RollGrappleClick(TObject *Sender);
        void __fastcall RollInitClick(TObject *Sender);
        void __fastcall RollFortClick(TObject *Sender);
        void __fastcall RollReflexClick(TObject *Sender);
        void __fastcall RollWillClick(TObject *Sender);
        void __fastcall RollMeleeClick(TObject *Sender);
        void __fastcall RollRangedClick(TObject *Sender);
        void __fastcall RollAttack1Click(TObject *Sender);
        void __fastcall RollAttack2Click(TObject *Sender);
        void __fastcall RollAttack3Click(TObject *Sender);
        void __fastcall RollAttack4Click(TObject *Sender);
        void __fastcall RollAttack5Click(TObject *Sender);
        void __fastcall Rolld4Click(TObject *Sender);
        void __fastcall Rolld6Click(TObject *Sender);
        void __fastcall Rolld8Click(TObject *Sender);
        void __fastcall Rolld10Click(TObject *Sender);
        void __fastcall Rolld12Click(TObject *Sender);
        void __fastcall Rolld20Click(TObject *Sender);
        void __fastcall Rolld100Click(TObject *Sender);
        void __fastcall RollDamage1Click(TObject *Sender);
        void __fastcall RollDamage2Click(TObject *Sender);
        void __fastcall RollDamage3Click(TObject *Sender);
        void __fastcall RollDamage4Click(TObject *Sender);
        void __fastcall RollDamage5Click(TObject *Sender);
        void __fastcall RollAppraiseClick(TObject *Sender);
        void __fastcall RollBalanceClick(TObject *Sender);
        void __fastcall RollBluffClick(TObject *Sender);
        void __fastcall RollClimbClick(TObject *Sender);
        void __fastcall RollConcentrationClick(TObject *Sender);
        void __fastcall RollDecipherScriptClick(TObject *Sender);
        void __fastcall RollDiplomacyClick(TObject *Sender);
        void __fastcall RollDisableDeviceClick(TObject *Sender);
        void __fastcall RollDisguiseClick(TObject *Sender);
        void __fastcall Button13Click(TObject *Sender);
        void __fastcall RollForgeryClick(TObject *Sender);
        void __fastcall Button15Click(TObject *Sender);
        void __fastcall RollHandleAnimalClick(TObject *Sender);
        void __fastcall RollHealClick(TObject *Sender);
        void __fastcall RollHideClick(TObject *Sender);
        void __fastcall RollIntimidateClick(TObject *Sender);
        void __fastcall RollJumpClick(TObject *Sender);
        void __fastcall RollListenClick(TObject *Sender);
        void __fastcall RollMoveSilentClick(TObject *Sender);
        void __fastcall RollOpenLockClick(TObject *Sender);
        void __fastcall RollRideClick(TObject *Sender);
        void __fastcall RollSearchClick(TObject *Sender);
        void __fastcall RollSenseMotiveClick(TObject *Sender);
        void __fastcall RollSleightofHandClick(TObject *Sender);
        void __fastcall RollSpellcraftClick(TObject *Sender);
        void __fastcall RollSpotClick(TObject *Sender);
        void __fastcall RollSurvivalClick(TObject *Sender);
        void __fastcall RollSwimClick(TObject *Sender);
        void __fastcall RollTumbleClick(TObject *Sender);
        void __fastcall RollUseMagicDeviceClick(TObject *Sender);
        void __fastcall RollUseRopeClick(TObject *Sender);
        void __fastcall RollCustom1Click(TObject *Sender);
        void __fastcall RollCustom2Click(TObject *Sender);
        void __fastcall RollCustom3Click(TObject *Sender);
        void __fastcall RollCraft1Click(TObject *Sender);
        void __fastcall RollCraft2Click(TObject *Sender);
        void __fastcall RollCraft3Click(TObject *Sender);
        void __fastcall RollKnowledge1Click(TObject *Sender);
        void __fastcall RollKnowledge2Click(TObject *Sender);
        void __fastcall RollKnowledge3Click(TObject *Sender);
        void __fastcall RollKnowledge4Click(TObject *Sender);
        void __fastcall RollKnowledge5Click(TObject *Sender);
        void __fastcall RollPerform1Click(TObject *Sender);
        void __fastcall RollPerform2Click(TObject *Sender);
        void __fastcall RollPerform3Click(TObject *Sender);
        void __fastcall RollProfession1Click(TObject *Sender);
        void __fastcall RollProfession2Click(TObject *Sender);
        void __fastcall Importv20Save1Click(TObject *Sender);
        void __fastcall New1Click(TObject *Sender);
        void __fastcall FormMouseWheelDown(TObject *Sender,
          TShiftState Shift, TPoint &MousePos, bool &Handled);
        void __fastcall FormMouseWheelUp(TObject *Sender,
          TShiftState Shift, TPoint &MousePos, bool &Handled);
        void __fastcall TXT1Click(TObject *Sender);
        void __fastcall Importv30Save1Click(TObject *Sender);
        void __fastcall XMLMapToolMacroXML1Click(TObject *Sender);
        void __fastcall ResetFonts1Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall TForm1(TComponent* Owner);
        //My one custom declaration ^_^
        bool RevertAsk;
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
